// ==================================
// PDF DOWNLOAD CONTROLLER
// ==================================

const PDFDocument = require('pdfkit');
const { Course } = require('../models/course');

// Helper: Strip HTML tags and decode entities
function stripHtml(html) {
    if (!html) return '';
    return html
        .replace(/<br\s*\/?>/gi, '\n')
        .replace(/<\/p>/gi, '\n\n')
        .replace(/<\/li>/gi, '\n')
        .replace(/<li>/gi, '  - ')
        .replace(/<\/h[1-6]>/gi, '\n')
        .replace(/<[^>]+>/g, '')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&nbsp;/g, ' ')
        .replace(/\n{3,}/g, '\n\n')
        .trim();
}

// Helper: Add styled header to PDF (for chapter-wise download)
function addHeader(doc, courseTitle, subtitle) {
    const titleHeight = doc.fontSize(24).font('Helvetica-Bold')
        .heightOfString(courseTitle, { width: doc.page.width - 80 });
    
    const subtitleHeight = subtitle ? doc.fontSize(11).font('Helvetica')
        .heightOfString(subtitle, { width: doc.page.width - 80 }) : 0;
    
    const headerHeight = 30 + titleHeight + (subtitle ? 8 + subtitleHeight : 0) + 8 + 14 + 20;
    
    doc.rect(0, 0, doc.page.width, headerHeight).fill('#7C3AED');
    
    let currentY = 25;
    doc.fontSize(24)
       .font('Helvetica-Bold')
       .fillColor('#FFFFFF')
       .text(courseTitle, 40, currentY, { width: doc.page.width - 80 });
    
    currentY += titleHeight + 8;
    
    if (subtitle) {
        doc.fontSize(11)
           .font('Helvetica')
           .fillColor('#E0D5FF')
           .text(subtitle, 40, currentY, { width: doc.page.width - 80 });
        currentY += subtitleHeight + 8;
    }
    
    doc.fontSize(9)
       .font('Helvetica-Bold')
       .fillColor('#E0D5FF')
       .text('Generated by GuideMe.AI', 40, currentY);
    
    doc.y = headerHeight + 15;
    doc.fillColor('#1F2937');
}

// Safe bottom margin - content should not go beyond this
const PAGE_BOTTOM_MARGIN = 60;

function getBottom(doc) {
    return doc.page.height - PAGE_BOTTOM_MARGIN;
}

// Helper: Safely add a new page only if we're not already at the top
function safeNewPage(doc) {
    // Only add a page if we've actually rendered content on the current one
    if (doc.y > doc.page.margins.top + 20) {
        doc.addPage();
    }
}

// Helper: Add chapter content to PDF
function addChapterToPdf(doc, chapter, chapterIdx, startOnNewPage) {
    if (startOnNewPage) {
        doc.addPage();
    }
    
    const BOTTOM = getBottom(doc);
    
    // Chapter header with purple accent bar
    const chapterY = doc.y;
    doc.rect(40, chapterY, 4, 30).fill('#7C3AED');
    
    doc.fontSize(20)
       .font('Helvetica-Bold')
       .fillColor('#1F2937')
       .text(`Chapter ${chapterIdx + 1}: ${chapter.chapter_title}`, 52, chapterY + 2, {
           width: doc.page.width - 100
       });
    
    doc.moveDown(1.5);
    
    const status = chapter.isCompleted ? '[Completed]' : '[In Progress]';
    doc.fontSize(10)
       .font('Helvetica')
       .fillColor('#6B7280')
       .text(status);
    
    doc.moveDown(1);
    
    doc.strokeColor('#E5E7EB')
       .lineWidth(1)
       .moveTo(40, doc.y)
       .lineTo(doc.page.width - 40, doc.y)
       .stroke();
    
    doc.moveDown(1);
    
    if (chapter.subtopics && chapter.subtopics.length > 0) {
        chapter.subtopics.forEach((sub, subIdx) => {
            if (doc.y > BOTTOM - 60) {
                doc.addPage();
            }
            
            // Subtopic title
            doc.fontSize(14)
               .font('Helvetica-Bold')
               .fillColor('#7C3AED')
               .text(`${subIdx + 1}. `, { continued: true })
               .fillColor('#374151')
               .text(sub.title);
            
            doc.moveDown(0.5);
            
            // Explanation - paragraph by paragraph to control page breaks
            if (sub.explanation) {
                const cleanText = stripHtml(sub.explanation);
                doc.fontSize(11)
                   .font('Helvetica')
                   .fillColor('#4B5563');
                
                const paragraphs = cleanText.split('\n\n').filter(p => p.trim());
                paragraphs.forEach(para => {
                    const trimmed = para.trim();
                    if (!trimmed) return;
                    
                    if (doc.y > BOTTOM - 40) {
                        doc.addPage();
                    }
                    doc.text(trimmed, {
                        width: doc.page.width - 80,
                        lineGap: 3
                    });
                    doc.moveDown(0.4);
                });
                doc.moveDown(0.3);
            }
            
            // Code block
            if (sub.code && sub.code !== 'null' && sub.code.trim() !== '') {
                const codeText = sub.code.trim();
                
                if (doc.y > BOTTOM - 80) {
                    doc.addPage();
                }
                
                doc.fontSize(9)
                   .font('Helvetica-Bold')
                   .fillColor('#9CA3AF')
                   .text('Code Example:', 50);
                doc.moveDown(0.3);
                
                const codeBlockY = doc.y;
                const spaceLeft = BOTTOM - codeBlockY;
                const maxBoxHeight = Math.min(spaceLeft, 280);
                const lineHeight = 11;
                const maxLines = Math.max(Math.floor((maxBoxHeight - 20) / lineHeight), 1);
                
                const allLines = codeText.split('\n');
                const visibleLines = allLines.slice(0, maxLines);
                let truncatedCode = visibleLines.join('\n');
                if (allLines.length > maxLines) {
                    truncatedCode += '\n// ... (truncated)';
                }
                
                const actualLines = truncatedCode.split('\n').length;
                const actualHeight = Math.min(actualLines * lineHeight + 20, maxBoxHeight);
                
                doc.rect(50, codeBlockY, doc.page.width - 100, actualHeight)
                   .fill('#1E1E1E');
                
                doc.fontSize(9)
                   .font('Courier')
                   .fillColor('#D4D4D4')
                   .text(truncatedCode, 60, codeBlockY + 10, {
                       width: doc.page.width - 120,
                       height: actualHeight - 15,
                       ellipsis: true
                   });
                
                doc.y = codeBlockY + actualHeight + 8;
                doc.x = 40;
            }
            
            // Specific topics
            if (sub.specific_topics && sub.specific_topics.length > 0) {
                sub.specific_topics.forEach(st => {
                    if (doc.y > BOTTOM - 60) {
                        doc.addPage();
                    }
                    
                    doc.fontSize(11)
                       .font('Helvetica-Bold')
                       .fillColor('#6D28D9')
                       .text(`> ${st.topic_name}`);
                    doc.moveDown(0.3);
                    
                    const stContent = stripHtml(st.content);
                    doc.fontSize(10)
                       .font('Helvetica')
                       .fillColor('#4B5563')
                       .text(stContent, {
                           width: doc.page.width - 80,
                           lineGap: 2
                       });
                    doc.moveDown(0.5);
                });
            }
            
            // Subtopic divider
            if (subIdx < chapter.subtopics.length - 1) {
                if (doc.y > BOTTOM - 30) {
                    doc.addPage();
                }
                doc.moveDown(0.3);
                doc.strokeColor('#F3F4F6')
                   .lineWidth(0.5)
                   .moveTo(60, doc.y)
                   .lineTo(doc.page.width - 60, doc.y)
                   .stroke();
                doc.moveDown(0.8);
            }
        });
    }
}

// ==========================================
// DOWNLOAD SINGLE CHAPTER PDF
// ==========================================
const downloadChapterPdf = async (req, res) => {
    try {
        const { courseId, chapterIndex } = req.params;
        
        const course = await Course.findById(courseId);
        if (!course) return res.status(404).json({ error: "Course not found" });
        
        const chIdx = parseInt(chapterIndex);
        if (isNaN(chIdx) || chIdx < 0 || chIdx >= course.chapters.length) {
            return res.status(400).json({ error: "Invalid chapter index" });
        }
        
        const chapter = course.chapters[chIdx];
        const fileName = `${course.title} - ${chapter.chapter_title}`.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '_');
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${fileName}.pdf"`);
        
        const doc = new PDFDocument({
            size: 'A4',
            margins: { top: 40, bottom: 60, left: 40, right: 40 },
            info: {
                Title: `${course.title} - ${chapter.chapter_title}`,
                Author: 'GuideMe.AI',
                Subject: course.title,
                Creator: 'GuideMe.AI PDF Generator'
            }
        });
        
        doc.pipe(res);
        
        addHeader(doc, course.title, `Chapter ${chIdx + 1}: ${chapter.chapter_title}`);
        addChapterToPdf(doc, chapter, chIdx, false);
        
        doc.end();
        
    } catch (error) {
        console.error("Chapter PDF Error:", error);
        if (!res.headersSent) {
            res.status(500).json({ error: "PDF generation failed" });
        }
    }
};

// ==========================================
// DOWNLOAD FULL COURSE PDF
// ==========================================
const downloadFullCoursePdf = async (req, res) => {
    try {
        const { courseId } = req.params;
        
        const course = await Course.findById(courseId);
        if (!course) return res.status(404).json({ error: "Course not found" });
        
        const fileName = `${course.title} - Complete Course`.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '_');
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${fileName}.pdf"`);
        
        const doc = new PDFDocument({
            size: 'A4',
            margins: { top: 40, bottom: 60, left: 40, right: 40 },
            info: {
                Title: `${course.title} - Complete Course`,
                Author: 'GuideMe.AI',
                Subject: course.title,
                Creator: 'GuideMe.AI PDF Generator'
            }
        });
        
        doc.pipe(res);
        
        // ===== COVER PAGE =====
        doc.rect(0, 0, doc.page.width, doc.page.height).fill('#7C3AED');
        doc.circle(450, 100, 150).fill('#8B5CF6');
        doc.circle(100, 700, 100).fill('#6D28D9');
        doc.circle(500, 600, 80).fill('#8B5CF6');
        
        doc.fontSize(38)
           .font('Helvetica-Bold')
           .fillColor('#FFFFFF')
           .text(course.title, 60, 250, {
               width: doc.page.width - 120,
               align: 'center'
           });
        
        if (course.description) {
            doc.moveDown(1);
            doc.fontSize(14)
               .font('Helvetica')
               .fillColor('#E0D5FF')
               .text(course.description, 60, doc.y, {
                   width: doc.page.width - 120,
                   align: 'center'
               });
        }
        
        doc.moveDown(2);
        const totalChapters = course.chapters.length;
        const totalSubtopics = course.chapters.reduce((sum, ch) => sum + (ch.subtopics ? ch.subtopics.length : 0), 0);
        
        doc.fontSize(12)
           .font('Helvetica')
           .fillColor('#C4B5FD')
           .text(`${totalChapters} Chapters  |  ${totalSubtopics} Topics`, 60, doc.y, {
               width: doc.page.width - 120,
               align: 'center'
           });
        
        doc.fontSize(14)
           .font('Helvetica-Bold')
           .fillColor('#FFFFFF')
           .text('GuideMe.AI', 60, doc.page.height - 100, {
               width: doc.page.width - 120,
               align: 'center'
           });
        
        doc.fontSize(10)
           .font('Helvetica')
           .fillColor('#C4B5FD')
           .text('Your AI-Powered Learning Companion', 60, doc.y + 5, {
               width: doc.page.width - 120,
               align: 'center'
           });
        
        // ===== TABLE OF CONTENTS =====
        doc.addPage();
        doc.rect(0, 0, doc.page.width, 80).fill('#7C3AED');
        doc.fontSize(24)
           .font('Helvetica-Bold')
           .fillColor('#FFFFFF')
           .text('Table of Contents', 40, 28);
        
        doc.y = 100;
        doc.fillColor('#1F2937');
        
        const BOTTOM = getBottom(doc);
        
        course.chapters.forEach((ch, idx) => {
            if (doc.y > BOTTOM - 60) {
                doc.addPage();
            }
            
            const statusTag = ch.isCompleted ? '[Done]' : '';
            
            doc.fontSize(13)
               .font('Helvetica-Bold')
               .fillColor('#7C3AED')
               .text(`Chapter ${idx + 1}`, 50, doc.y, { continued: true })
               .fillColor('#374151')
               .text(`  ${ch.chapter_title}  `, { continued: !!statusTag });
            
            if (statusTag) {
                doc.fontSize(10)
                   .font('Helvetica')
                   .fillColor('#059669')
                   .text(statusTag);
            }
            
            if (ch.subtopics && ch.subtopics.length > 0) {
                ch.subtopics.forEach(sub => {
                    doc.fontSize(10)
                       .font('Helvetica')
                       .fillColor('#6B7280')
                       .text(`      -  ${sub.title}`, { indent: 20 });
                });
            }
            
            doc.moveDown(0.8);
        });
        
        // ===== CHAPTER CONTENT =====
        course.chapters.forEach((chapter, idx) => {
            addChapterToPdf(doc, chapter, idx, true);
        });
        
        doc.end();
        
    } catch (error) {
        console.error("Full Course PDF Error:", error);
        if (!res.headersSent) {
            res.status(500).json({ error: "PDF generation failed" });
        }
    }
};

module.exports = {
    downloadChapterPdf,
    downloadFullCoursePdf
};
